/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Mvc.Model;
import Mvc.View;
import Transactions.Event;
import Transactions.TransactionInvoker;
import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author Equipo1
 */
public class FormVotar extends View {

    public FormVotar(Model model) {
        super(model);
        initComponents();

        Event event = new Event("Iniciar-formulario");
        event.addParam("view", this);
        TransactionInvoker invoker = TransactionInvoker.getInstance();
        invoker.invokeAction("rellenar-combo", event);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComboCandidatos = new javax.swing.JComboBox<>();
        BtnVotar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnReiniciarVotos = new javax.swing.JButton();
        BtnAgregarCandidato = new javax.swing.JButton();
        BtnBorrarCandidato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de votacion");

        ComboCandidatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BtnVotar.setText("Votar");
        BtnVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVotarActionPerformed(evt);
            }
        });

        jLabel2.setText("Candidatos:");

        BtnReiniciarVotos.setText("Reiniciar votos");
        BtnReiniciarVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReiniciarVotosActionPerformed(evt);
            }
        });

        BtnAgregarCandidato.setText("Agregar candidato");
        BtnAgregarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarCandidatoActionPerformed(evt);
            }
        });

        BtnBorrarCandidato.setText("Borrar candidato");
        BtnBorrarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarCandidatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(BtnAgregarCandidato)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnVotar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnBorrarCandidato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(BtnReiniciarVotos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(ComboCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addComponent(BtnVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnReiniciarVotos)
                    .addComponent(BtnAgregarCandidato)
                    .addComponent(BtnBorrarCandidato))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVotarActionPerformed
        String candidato = getComboCandidatos().getSelectedItem().toString();
        Event event = new Event("Votar");
        event.addParam("candidato", candidato);

        TransactionInvoker invoker = TransactionInvoker.getInstance();
        invoker.invokeAction("votar", event);
    }//GEN-LAST:event_BtnVotarActionPerformed

    private void BtnReiniciarVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReiniciarVotosActionPerformed
        TransactionInvoker invoker = TransactionInvoker.getInstance();
        invoker.invokeAction("reiniciar-votos", new Event("Reiniciar-votos"));
    }//GEN-LAST:event_BtnReiniciarVotosActionPerformed

    private void BtnAgregarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarCandidatoActionPerformed
        Event event = new Event("Agregar-candidato");
        event.addParam("view", this);
        
        TransactionInvoker invoker = TransactionInvoker.getInstance();
        invoker.invokeAction("agregar-candidato", event);
    }//GEN-LAST:event_BtnAgregarCandidatoActionPerformed

    private void BtnBorrarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarCandidatoActionPerformed
        Event event = new Event("Borrar-candidato");
        event.addParam("view", this);
        
        TransactionInvoker invoker = TransactionInvoker.getInstance();
        invoker.invokeAction("eliminar-candidato", event);
    }//GEN-LAST:event_BtnBorrarCandidatoActionPerformed

    public JButton getBtnReiniciarVotos() {
        return BtnReiniciarVotos;
    }

    public void setBtnReiniciarVotos(JButton BtnReiniciarVotos) {
        this.BtnReiniciarVotos = BtnReiniciarVotos;
    }

    public JButton getBtnVotar() {
        return BtnVotar;
    }

    public void setBtnVotar(JButton BtnVotar) {
        this.BtnVotar = BtnVotar;
    }

    public JComboBox<String> getComboCandidatos() {
        return ComboCandidatos;
    }

    public void setComboCandidatos(JComboBox<String> ComboCandidatos) {
        this.ComboCandidatos = ComboCandidatos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarCandidato;
    private javax.swing.JButton BtnBorrarCandidato;
    private javax.swing.JButton BtnReiniciarVotos;
    private javax.swing.JButton BtnVotar;
    private javax.swing.JComboBox<String> ComboCandidatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        
    }
  
}
